package modelo.entidad;


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Cargos generated by hbm2java
 */
public class Cargos  implements java.io.Serializable {


     private int idcargo;
     private String nombre;
     private BigDecimal salario;
     private Set empleados = new HashSet(0);

    public Cargos() {
    }

    public Cargos(int idcargo, String nombre, BigDecimal salario) {
        this.idcargo = idcargo;
        this.nombre = nombre;
        this.salario = salario;
    }

    public Cargos(String nombre, BigDecimal salario) {
        this.nombre = nombre;
        this.salario = salario;
    }

	
    public Cargos(int idcargo) {
        this.idcargo = idcargo;
    }
    public Cargos(int idcargo, String nombre, BigDecimal salario, Set empleados) {
       this.idcargo = idcargo;
       this.nombre = nombre;
       this.salario = salario;
       this.empleados = empleados;
    }
   
    public int getIdcargo() {
        return this.idcargo;
    }
    
    public void setIdcargo(int idcargo) {
        this.idcargo = idcargo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public BigDecimal getSalario() {
        return this.salario;
    }
    
    public void setSalario(BigDecimal salario) {
        this.salario = salario;
    }
    public Set getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }




}


