package modelo.entidad;


import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private int idcliente;
     private String nombres;
     private String apellidos;
     private String tipodocu;
     private String numdocu;
     private String direccion;
     private String telefono;
     private Set reservas = new HashSet(0);

    public Clientes() {
    }

    public Clientes(int idcliente, String nombres, String apellidos, String tipodocu, String numdocu, String direccion, String telefono) {
        this.idcliente = idcliente;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.tipodocu = tipodocu;
        this.numdocu = numdocu;
        this.direccion = direccion;
        this.telefono = telefono;
    }

	
    public Clientes(int idcliente) {
        this.idcliente = idcliente;
    }
    public Clientes(int idcliente, String nombres, String apellidos, String tipodocu, String numdocu, String direccion, String telefono, Set reservas) {
       this.idcliente = idcliente;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.tipodocu = tipodocu;
       this.numdocu = numdocu;
       this.direccion = direccion;
       this.telefono = telefono;
       this.reservas = reservas;
    }
   
    public int getIdcliente() {
        return this.idcliente;
    }
    
    public void setIdcliente(int idcliente) {
        this.idcliente = idcliente;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getTipodocu() {
        return this.tipodocu;
    }
    
    public void setTipodocu(String tipodocu) {
        this.tipodocu = tipodocu;
    }
    public String getNumdocu() {
        return this.numdocu;
    }
    
    public void setNumdocu(String numdocu) {
        this.numdocu = numdocu;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }




}


