package modelo.entidad;


import java.math.BigDecimal;

/**
 * Consumo generated by hbm2java
 */
public class Consumo implements java.io.Serializable {

    private int idconsumo;
    private Producto producto;
    private Reserva reserva;
    private Integer cantidad;

    public Consumo() {
    }

    public Consumo(int idconsumo) {
        this.idconsumo = idconsumo;
    }

    public Consumo(int idconsumo, Producto producto, Reserva reserva) {
        this.idconsumo = idconsumo;
        this.producto = producto;
        this.reserva = reserva;
    }

    public Consumo(int idconsumo, Producto producto, Reserva reserva, Integer cantidad) {
        this.idconsumo = idconsumo;
        this.producto = producto;
        this.reserva = reserva;
        this.cantidad = cantidad;
    }

    public int getIdconsumo() {
        return this.idconsumo;
    }

    public void setIdconsumo(int idconsumo) {
        this.idconsumo = idconsumo;
    }

    public Producto getProducto() {
        return this.producto;
    }

    public void setProducto(Producto producto) {
        this.producto = producto;
    }

    public Reserva getReserva() {
        return this.reserva;
    }

    public void setReserva(Reserva reserva) {
        this.reserva = reserva;
    }

    public Integer getCantidad() {
        return this.cantidad;
    }

    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }

    public Double total() {
        Double tot = Double.parseDouble(String.valueOf(producto.getPrecioventa())) * getCantidad();
        return tot;
    }
}
