package modelo.entidad;



import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Habitacion generated by hbm2java
 */
public class Habitacion  implements java.io.Serializable {


     private int idhabitacion;
     private String numero;
     private String piso;
     private String descripcion;
     private String caracteristicas;
     private BigDecimal preciodiario;
     private String estado;
     private String tipohabitacion;
     private Set reservas = new HashSet(0);

    public Habitacion() {
    }

	
    public Habitacion(int idhabitacion) {
        this.idhabitacion = idhabitacion;
    }

    public Habitacion(int idhabitacion, String numero, String piso, String descripcion, String caracteristicas, BigDecimal preciodiario, String estado, String tipohabitacion) {
        this.idhabitacion = idhabitacion;
        this.numero = numero;
        this.piso = piso;
        this.descripcion = descripcion;
        this.caracteristicas = caracteristicas;
        this.preciodiario = preciodiario;
        this.estado = estado;
        this.tipohabitacion = tipohabitacion;
    }
    public Habitacion(int idhabitacion, String numero, String piso, String descripcion, String caracteristicas, BigDecimal preciodiario, String estado, String tipohabitacion, Set reservas) {
       this.idhabitacion = idhabitacion;
       this.numero = numero;
       this.piso = piso;
       this.descripcion = descripcion;
       this.caracteristicas = caracteristicas;
       this.preciodiario = preciodiario;
       this.estado = estado;
       this.tipohabitacion = tipohabitacion;
       this.reservas = reservas;
    }
   
    public int getIdhabitacion() {
        return this.idhabitacion;
    }
    
    public void setIdhabitacion(int idhabitacion) {
        this.idhabitacion = idhabitacion;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public String getPiso() {
        return this.piso;
    }
    
    public void setPiso(String piso) {
        this.piso = piso;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getCaracteristicas() {
        return this.caracteristicas;
    }
    
    public void setCaracteristicas(String caracteristicas) {
        this.caracteristicas = caracteristicas;
    }
    public BigDecimal getPreciodiario() {
        return this.preciodiario;
    }
    
    public void setPreciodiario(BigDecimal preciodiario) {
        this.preciodiario = preciodiario;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getTipohabitacion() {
        return this.tipohabitacion;
    }
    
    public void setTipohabitacion(String tipohabitacion) {
        this.tipohabitacion = tipohabitacion;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }




}


