package modelo.entidad;



import java.math.BigDecimal;
import java.util.Date;

/**
 * Pago generated by hbm2java
 */
public class Pago  implements java.io.Serializable {


     private int idpago;
     private Reserva reserva;
     private String tipocomprobante;
     private String numcomprobante;
     private BigDecimal igv;
     private Date fechaemision;
     private Date fechapago;

    public Pago() {
    }

    public Pago(int idpago) {
        this.idpago = idpago;
    }

	
    public Pago(int idpago, Reserva reserva) {
        this.idpago = idpago;
        this.reserva = reserva;
    }
    public Pago(int idpago, Reserva reserva, String tipocomprobante, String numcomprobante, BigDecimal igv, Date fechaemision, Date fechapago) {
       this.idpago = idpago;
       this.reserva = reserva;
       this.tipocomprobante = tipocomprobante;
       this.numcomprobante = numcomprobante;
       this.igv = igv;
       this.fechaemision = fechaemision;
       this.fechapago = fechapago;
    }
   
    public int getIdpago() {
        return this.idpago;
    }
    
    public void setIdpago(int idpago) {
        this.idpago = idpago;
    }
    public Reserva getReserva() {
        return this.reserva;
    }
    
    public void setReserva(Reserva reserva) {
        this.reserva = reserva;
    }
    public String getTipocomprobante() {
        return this.tipocomprobante;
    }
    
    public void setTipocomprobante(String tipocomprobante) {
        this.tipocomprobante = tipocomprobante;
    }
    public String getNumcomprobante() {
        return this.numcomprobante;
    }
    
    public void setNumcomprobante(String numcomprobante) {
        this.numcomprobante = numcomprobante;
    }
    public BigDecimal getIgv() {
        return this.igv;
    }
    
    public void setIgv(BigDecimal igv) {
        this.igv = igv;
    }
    public Date getFechaemision() {
        return this.fechaemision;
    }
    
    public void setFechaemision(Date fechaemision) {
        this.fechaemision = fechaemision;
    }
    public Date getFechapago() {
        return this.fechapago;
    }
    
    public void setFechapago(Date fechapago) {
        this.fechapago = fechapago;
    }




}


