package modelo.entidad;



import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private int idproducto;
     private Categoria categoria;
     private String nombre;
     private String descripcion;
     private BigDecimal precioventa;
     private Set consumos = new HashSet(0);

    public Producto() {
    }

    public Producto(int idproducto) {
        this.idproducto = idproducto;
    }

    public Producto(int idproducto, Categoria categoria, String nombre, String descripcion, BigDecimal precioventa) {
        this.idproducto = idproducto;
        this.categoria = categoria;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.precioventa = precioventa;
    }

	
    public Producto(int idproducto, Categoria categoria) {
        this.idproducto = idproducto;
        this.categoria = categoria;
    }
    public Producto(int idproducto, Categoria categoria, String nombre, String descripcion, BigDecimal precioventa, Set consumos) {
       this.idproducto = idproducto;
       this.categoria = categoria;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.precioventa = precioventa;
       this.consumos = consumos;
    }
   
    public int getIdproducto() {
        return this.idproducto;
    }
    
    public void setIdproducto(int idproducto) {
        this.idproducto = idproducto;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public BigDecimal getPrecioventa() {
        return this.precioventa;
    }
    
    public void setPrecioventa(BigDecimal precioventa) {
        this.precioventa = precioventa;
    }
    public Set getConsumos() {
        return this.consumos;
    }
    
    public void setConsumos(Set consumos) {
        this.consumos = consumos;
    }




}


