package modelo.entidad;




/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private int idusuario;
     private Empleado empleado;
     private String usuario;
     private String password;

    public Usuarios() {
    }

    public Usuarios(int idusuario) {
        this.idusuario = idusuario;
    }

	
    public Usuarios(int idusuario, Empleado empleado) {
        this.idusuario = idusuario;
        this.empleado = empleado;
    }
    public Usuarios(int idusuario, Empleado empleado, String usuario, String password) {
       this.idusuario = idusuario;
       this.empleado = empleado;
       this.usuario = usuario;
       this.password = password;
    }
   
    public int getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
}


